apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: amazon/aws-for-fluent-bit:latest # aws fluent offical docker image
        env:
        - name: AWS_REGION
          value: "us-east-1" 
        - name: OPENSEARCH_HOST
          value: "https://your-opensearch-endpoint" # change correct OpenSearch endpoint for logs
        - name: OPENSEARCH_PORT
          value: "443"